_specver: 2

modpack:
  name: All of Fabric 4
  description: Modpack containing the latest & best Fabric mods on 1.17.1
  
install:
  mcVersion: 1.17.1
  loaderVersion: 0.11.7
  modpackUrl: https://github.com/TeamAOF/All-of-Fabric-4/releases/download/server-pack/All.of.Fabric.4-ServerPack.zip
  installerUrl: https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.7.3/fabric-installer-0.7.3.jar
  
  ignoreFiles:
    - mods/optifine*.jar
    - resources/**
  additionalFiles:
    # Additional mods not available on Curseforge
    # With this mod installed boats will break when they fall from a great enough
    # height and their passengers will take the appropriate amount of fall damage.
    - url: https://cdn.modrinth.com/data/R1GcscrS/versions/1.0.0/boat-fall-1.0.0.jar
      destination: mods/boat-fall-1.0.0.jar
    # Helps Identify mods that crash inside a mixin
    - url: https://github.com/Chocohead/Crafty-Crashes/releases/download/v1.0/Crafty-Crashes-1.0.jar
      destination: mods/Crafty-Crashes-1.0.jar
    # Allows players to opt in to pvp or not. Per player setting.
    - url: https://github.com/manyrandomthings/pvp-toggle/releases/download/1.0.4/pvp-toggle-1.0.4.jar
      destination: mods/pvp-toggle-1.0.4.jar
    # Extends the default timeout limit to help limit connection issues
    - url: https://github.com/PotatoPresident/TimeOutOut/releases/download/1.0.0/timeoutout-1.0.0.jar
      destination: mods/timeoutout-1.0.0.jar

  localFiles: ~
  
  installerArguments:
    - "server"
    - "-downloadMinecraft"
    - "-snapshot"
    - "-mcversion"
    - "1.17.1"
    - "-loader"
    - "0.11.7"
  modpackFormat: curse
  formatSpecific:
    ignoreProject: []
  baseInstallPath: ~
  checkFolder: yes
  installLoader: yes
  spongeBootstrapper: ~

launch:
  # specifies the max amount of ram the server is supposed to launch with (Xmx)
  maxRam: 4G
  # specifies the minimal amount of ram the server is supposed to launch with (Xms)
  minRam: 4G
  # specifies whether the server is supposed to auto restart after crash
  autoRestart: yes
  javaArgs:
    - "-server"
    - "-XX:+UseG1GC"
    - "-XX:+ParallelRefProcEnabled"
    - "-XX:MaxGCPauseMillis=100"
    - "-XX:+UnlockExperimentalVMOptions"
    - "-XX:+DisableExplicitGC"
    - "-XX:+AlwaysPreTouch"
    - "-XX:G1NewSizePercent=30"
    - "-XX:G1MaxNewSizePercent=40"
    - "-XX:G1HeapRegionSize=8M"
    - "-XX:G1ReservePercent=20"
    - "-XX:G1HeapWastePercent=5" 
    - "-XX:G1MixedGCCountTarget=4" 
    - "-XX:InitiatingHeapOccupancyPercent=15" 
    - "-XX:G1MixedGCLiveThresholdPercent=90" 
    - "-XX:G1RSetUpdatingPauseTimePercent=5" 
    - "-XX:SurvivorRatio=32" 
    - "-XX:+PerfDisableSharedMem" 
    - "-XX:MaxTenuringThreshold=1" 
    - "-Dusing.aikars.flags=https://mcflags.emc.gs" 
    - "-Daikars.new.flags=true"
    
  spongefix: no
  ramDisk: no
  checkOffline: no
  crashLimit: 10
  crashTimer: 60min
  preJavaArgs: ~
  startFile: fabric-server-launch.jar
  forcedJavaPath: ~


